@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 07 09:11:22 +0800 2021
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Calculate_Parellel_TB_behav -key {Behavioral:Calculate_Parellel_TB:Functional:Calculate_Parellel_TB} -tclbatch Calculate_Parellel_TB.tcl -view D:/DigitalLogic/1024BitsLargeMultiplication/1024BitsLargeMultiplication.srcs/Calculate_Parellel_TB/imports/DigitalLogic/WaveFormConfigFile/1024BitsLargeMultiplication/Calculate_Parellel_TB_behav.wcfg -log simulate.log"
call xsim  Calculate_Parellel_TB_behav -key {Behavioral:Calculate_Parellel_TB:Functional:Calculate_Parellel_TB} -tclbatch Calculate_Parellel_TB.tcl -view D:/DigitalLogic/1024BitsLargeMultiplication/1024BitsLargeMultiplication.srcs/Calculate_Parellel_TB/imports/DigitalLogic/WaveFormConfigFile/1024BitsLargeMultiplication/Calculate_Parellel_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
